In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Data is pulled and initial cleaning is done

# Data is pulled from csv
raw_data_df = pd.read_csv("data/state_populations.csv")
raw_data_df

# Iterate through rows deleting periods and commas
for index, row in raw_data_df.iterrows():
    
    # Period is deleted from jurisdiction
    row[0] = row[0].replace(".", "")
    
    # Commas are deleted from numbers, which are then converted to integers
    row[1] = int(row[1].replace(",",""))
    row[2] = int(row[2].replace(",",""))
    row[3] = int(row[3].replace(",",""))
    row[4] = int(row[4].replace(",",""))
    row[5] = int(row[5].replace(",",""))
    row[6] = int(row[6].replace(",",""))
    row[7] = int(row[7].replace(",",""))
    
raw_data_df

,jurisdiction,pop_2014,pop_2015,pop_2016,pop_2017,pop_2018,pop_2019,pop_2020
0,Alabama,4841799,4852347,4863525,4874486,4887681,4903185,4911278
1,Alaska,736283,737498,741456,739700,735139,731545,751328
2,Arizona,6730413,6829676,6941072,7044008,7158024,7278717,7268694
3,Arkansas,2967392,2978048,2989918,3001345,3009733,3017804,3038491
4,California,38596972,38918045,39167117,39358497,39461588,39512223,40438640
5,Colorado,5350101,5450623,5539215,5611885,5691287,5758736,5843359
6,Connecticut,3594524,3587122,3578141,3573297,3571520,3565287,3593542
7,Delaware,932487,941252,948921,956823,965479,973764,987393
8,District of Columbia,662328,675400,685815,694906,701547,705749,732552
9,Florida,19845911,20209042,20613477,20963613,21244317,21477737,21877257
10,Georgia,10067278,10178447,10301890,10410330,10511131,10617423,10725351
11,Hawaii,1414538,1422052,1427559,1424393,1420593,1415872,1453902
12,Idaho,1631112,1651059,1682380,1717715,1750536,1787065,1777249
13,Illinois,12884493,12858913,12820527,12778828,12723071,12671821,12791188
14,Indiana,6593644,6608422,6634304,6658078,6695497,6732219,6737581
15,Iowa,3109350,3120960,3131371,3141550,3148618,3155070,3184240
16,Kansas,2900475,2909011,2910844,2908718,2911359,2913314,2936212
17,Kentucky,4414349,4425976,4438182,4452268,4461153,4467673,4498533
18,Louisiana,4644013,4664628,4678135,4670560,4659690,4648794,4742900
19,Maine,1330513,1328262,1331317,1334612,1339057,1344212,1338780
20,Maryland,5957283,5985562,6003323,6023868,6035802,6045680,6161345
21,Massachusetts,6762596,6794228,6823608,6859789,6882635,6892503,6982092
22,Michigan,9929848,9931715,9950571,9973114,9984072,9986857,9992315
23,Minnesota,5451079,5482032,5522744,5566230,5606249,5639632,5683666
24,Mississippi,2990468,2988471,2987938,2988510,2981020,2976149,2990498
25,Missouri,6056202,6071732,6087135,6106670,6121623,6137428,6161471
26,Montana,1021869,1030475,1040859,1052482,1060665,1068778,1074635
27,Nebraska,1879321,1891277,1905616,1915947,1925614,1934408,1956876
28,Nevada,2817628,2866939,2917563,2969905,3027341,3080156,3119265
29,New Hampshire,1333341,1336350,1342307,1348787,1353465,1359711,1352917
30,New Jersey,8864525,8867949,8870827,8885525,8886025,8882190,9088074
31,New Mexico,2089568,2089291,2091630,2091784,2092741,2096829,2099134
32,New York,19651049,19654666,19633428,19589572,19530351,19453561,20031150
33,North Carolina,9932887,10031646,10154788,10268233,10381615,10488084,10568033
34,North Dakota,737401,754066,754434,754942,758080,762062,789403
35,Ohio,11602700,11617527,11634370,11659650,11676341,11689100,11705262
36,Oklahoma,3878187,3909500,3926331,3931316,3940235,3956971,4001180
37,Oregon,3963244,4015792,4089976,4143625,4181886,4217737,4267534
38,Pennsylvania,12788313,12784826,12782275,12787641,12800922,12801989,12844885
39,Rhode Island,1055936,1056065,1056770,1055673,1058287,1059361,1062334
40,South Carolina,4823617,4891938,4957968,5021268,5084156,5148714,5184564
41,South Dakota,849129,853988,862996,872868,878698,884659,891688
42,Tennessee,6541223,6591170,6646010,6708799,6771631,6829174,6861856
43,Texas,26964333,27470056,27914410,28295273,28628666,28995881,29604099
44,Utah,2936879,2981835,3041868,3101042,3153550,3205958,3240569
45,Vermont,625214,625216,623657,624344,624358,623989,622868
46,Virginia,8310993,8361808,8410106,8463587,8501286,8535519,8655021
47,Washington,7054655,7163657,7294771,7423362,7523869,7614893,7681818
48,West Virginia,1849489,1842050,1831023,1817004,1804291,1792147,1801966
49,Wisconsin,5751525,5760940,5772628,5790186,5807406,5822434,5837176
50,Wyoming,582531,585613,584215,578931,577601,578759,585380

In [3]:
# Jurisdictions with bad data are dropped

# Array of jurisdictions to drop
juri_to_drop = ["Connecticut", "North Carolina", "District of Columbia"]

# Dataframe for the jurisdictions to drop. Flip the boolean to get without the jurisdictions.
data_states = raw_data_df[raw_data_df['jurisdiction'].isin(juri_to_drop) == True]
data_states

,jurisdiction,pop_2014,pop_2015,pop_2016,pop_2017,pop_2018,pop_2019,pop_2020
6,Connecticut,3594524,3587122,3578141,3573297,3571520,3565287,3593542
8,District of Columbia,662328,675400,685815,694906,701547,705749,732552
33,North Carolina,9932887,10031646,10154788,10268233,10381615,10488084,10568033

In [4]:
# Dataframe containing only desired states
wanted_juri_df = raw_data_df[raw_data_df['jurisdiction'].isin(juri_to_drop) == False]
wanted_juri_df

,jurisdiction,pop_2014,pop_2015,pop_2016,pop_2017,pop_2018,pop_2019,pop_2020
0,Alabama,4841799,4852347,4863525,4874486,4887681,4903185,4911278
1,Alaska,736283,737498,741456,739700,735139,731545,751328
2,Arizona,6730413,6829676,6941072,7044008,7158024,7278717,7268694
3,Arkansas,2967392,2978048,2989918,3001345,3009733,3017804,3038491
4,California,38596972,38918045,39167117,39358497,39461588,39512223,40438640
5,Colorado,5350101,5450623,5539215,5611885,5691287,5758736,5843359
7,Delaware,932487,941252,948921,956823,965479,973764,987393
9,Florida,19845911,20209042,20613477,20963613,21244317,21477737,21877257
10,Georgia,10067278,10178447,10301890,10410330,10511131,10617423,10725351
11,Hawaii,1414538,1422052,1427559,1424393,1420593,1415872,1453902
12,Idaho,1631112,1651059,1682380,1717715,1750536,1787065,1777249
13,Illinois,12884493,12858913,12820527,12778828,12723071,12671821,12791188
14,Indiana,6593644,6608422,6634304,6658078,6695497,6732219,6737581
15,Iowa,3109350,3120960,3131371,3141550,3148618,3155070,3184240
16,Kansas,2900475,2909011,2910844,2908718,2911359,2913314,2936212
17,Kentucky,4414349,4425976,4438182,4452268,4461153,4467673,4498533
18,Louisiana,4644013,4664628,4678135,4670560,4659690,4648794,4742900
19,Maine,1330513,1328262,1331317,1334612,1339057,1344212,1338780
20,Maryland,5957283,5985562,6003323,6023868,6035802,6045680,6161345
21,Massachusetts,6762596,6794228,6823608,6859789,6882635,6892503,6982092
22,Michigan,9929848,9931715,9950571,9973114,9984072,9986857,9992315
23,Minnesota,5451079,5482032,5522744,5566230,5606249,5639632,5683666
24,Mississippi,2990468,2988471,2987938,2988510,2981020,2976149,2990498
25,Missouri,6056202,6071732,6087135,6106670,6121623,6137428,6161471
26,Montana,1021869,1030475,1040859,1052482,1060665,1068778,1074635
27,Nebraska,1879321,1891277,1905616,1915947,1925614,1934408,1956876
28,Nevada,2817628,2866939,2917563,2969905,3027341,3080156,3119265
29,New Hampshire,1333341,1336350,1342307,1348787,1353465,1359711,1352917
30,New Jersey,8864525,8867949,8870827,8885525,8886025,8882190,9088074
31,New Mexico,2089568,2089291,2091630,2091784,2092741,2096829,2099134
32,New York,19651049,19654666,19633428,19589572,19530351,19453561,20031150
34,North Dakota,737401,754066,754434,754942,758080,762062,789403
35,Ohio,11602700,11617527,11634370,11659650,11676341,11689100,11705262
36,Oklahoma,3878187,3909500,3926331,3931316,3940235,3956971,4001180
37,Oregon,3963244,4015792,4089976,4143625,4181886,4217737,4267534
38,Pennsylvania,12788313,12784826,12782275,12787641,12800922,12801989,12844885
39,Rhode Island,1055936,1056065,1056770,1055673,1058287,1059361,1062334
40,South Carolina,4823617,4891938,4957968,5021268,5084156,5148714,5184564
41,South Dakota,849129,853988,862996,872868,878698,884659,891688
42,Tennessee,6541223,6591170,6646010,6708799,6771631,6829174,6861856
43,Texas,26964333,27470056,27914410,28295273,28628666,28995881,29604099
44,Utah,2936879,2981835,3041868,3101042,3153550,3205958,3240569
45,Vermont,625214,625216,623657,624344,624358,623989,622868
46,Virginia,8310993,8361808,8410106,8463587,8501286,8535519,8655021
47,Washington,7054655,7163657,7294771,7423362,7523869,7614893,7681818
48,West Virginia,1849489,1842050,1831023,1817004,1804291,1792147,1801966
49,Wisconsin,5751525,5760940,5772628,5790186,5807406,5822434,5837176
50,Wyoming,582531,585613,584215,578931,577601,578759,585380

In [5]:
# Dataframe for summed populations is crafted then appended to dataframe
summed_pop_df = pd.DataFrame([["United States (w/o dropped)", wanted_juri_df["pop_2014"].sum(),
                             wanted_juri_df["pop_2015"].sum(),
                             wanted_juri_df["pop_2016"].sum(),
                             wanted_juri_df["pop_2017"].sum(),
                             wanted_juri_df["pop_2018"].sum(),
                             wanted_juri_df["pop_2019"].sum(),
                             wanted_juri_df["pop_2020"].sum()]],
                             columns=["jurisdiction","pop_2014","pop_2015","pop_2016","pop_2017",
                                      "pop_2018","pop_2019","pop_2020",])

final_2014_2018_df = wanted_juri_df.append(summed_pop_df)
final_2014_2018_df

,jurisdiction,pop_2014,pop_2015,pop_2016,pop_2017,pop_2018,pop_2019,pop_2020
0,Alabama,4841799,4852347,4863525,4874486,4887681,4903185,4911278
1,Alaska,736283,737498,741456,739700,735139,731545,751328
2,Arizona,6730413,6829676,6941072,7044008,7158024,7278717,7268694
3,Arkansas,2967392,2978048,2989918,3001345,3009733,3017804,3038491
4,California,38596972,38918045,39167117,39358497,39461588,39512223,40438640
5,Colorado,5350101,5450623,5539215,5611885,5691287,5758736,5843359
7,Delaware,932487,941252,948921,956823,965479,973764,987393
9,Florida,19845911,20209042,20613477,20963613,21244317,21477737,21877257
10,Georgia,10067278,10178447,10301890,10410330,10511131,10617423,10725351
11,Hawaii,1414538,1422052,1427559,1424393,1420593,1415872,1453902
12,Idaho,1631112,1651059,1682380,1717715,1750536,1787065,1777249
13,Illinois,12884493,12858913,12820527,12778828,12723071,12671821,12791188
14,Indiana,6593644,6608422,6634304,6658078,6695497,6732219,6737581
15,Iowa,3109350,3120960,3131371,3141550,3148618,3155070,3184240
16,Kansas,2900475,2909011,2910844,2908718,2911359,2913314,2936212
17,Kentucky,4414349,4425976,4438182,4452268,4461153,4467673,4498533
18,Louisiana,4644013,4664628,4678135,4670560,4659690,4648794,4742900
19,Maine,1330513,1328262,1331317,1334612,1339057,1344212,1338780
20,Maryland,5957283,5985562,6003323,6023868,6035802,6045680,6161345
21,Massachusetts,6762596,6794228,6823608,6859789,6882635,6892503,6982092
22,Michigan,9929848,9931715,9950571,9973114,9984072,9986857,9992315
23,Minnesota,5451079,5482032,5522744,5566230,5606249,5639632,5683666
24,Mississippi,2990468,2988471,2987938,2988510,2981020,2976149,2990498
25,Missouri,6056202,6071732,6087135,6106670,6121623,6137428,6161471
26,Montana,1021869,1030475,1040859,1052482,1060665,1068778,1074635
27,Nebraska,1879321,1891277,1905616,1915947,1925614,1934408,1956876
28,Nevada,2817628,2866939,2917563,2969905,3027341,3080156,3119265
29,New Hampshire,1333341,1336350,1342307,1348787,1353465,1359711,1352917
30,New Jersey,8864525,8867949,8870827,8885525,8886025,8882190,9088074
31,New Mexico,2089568,2089291,2091630,2091784,2092741,2096829,2099134
32,New York,19651049,19654666,19633428,19589572,19530351,19453561,20031150
34,North Dakota,737401,754066,754434,754942,758080,762062,789403
35,Ohio,11602700,11617527,11634370,11659650,11676341,11689100,11705262
36,Oklahoma,3878187,3909500,3926331,3931316,3940235,3956971,4001180
37,Oregon,3963244,4015792,4089976,4143625,4181886,4217737,4267534
38,Pennsylvania,12788313,12784826,12782275,12787641,12800922,12801989,12844885
39,Rhode Island,1055936,1056065,1056770,1055673,1058287,1059361,1062334
40,South Carolina,4823617,4891938,4957968,5021268,5084156,5148714,5184564
41,South Dakota,849129,853988,862996,872868,878698,884659,891688
42,Tennessee,6541223,6591170,6646010,6708799,6771631,6829174,6861856
43,Texas,26964333,27470056,27914410,28295273,28628666,28995881,29604099
44,Utah,2936879,2981835,3041868,3101042,3153550,3205958,3240569
45,Vermont,625214,625216,623657,624344,624358,623989,622868
46,Virginia,8310993,8361808,8410106,8463587,8501286,8535519,8655021
47,Washington,7054655,7163657,7294771,7423362,7523869,7614893,7681818
48,West Virginia,1849489,1842050,1831023,1817004,1804291,1792147,1801966
49,Wisconsin,5751525,5760940,5772628,5790186,5807406,5822434,5837176
50,Wyoming,582531,585613,584215,578931,577601,578759,585380
0,United States (w/o dropped),304111269,306340995,308522567,310449103,312032819,313480403,317633417