In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Grab relevant dataframes and append them
death_2014_2018_df = pd.read_csv("data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2014-2018_studydata.csv")
death_2019_2020_df = pd.read_csv("data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2019-2020_studydata.csv")
death_2014_2020_df = death_2014_2018_df.append(death_2019_2020_df)


death_2014_2020_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,Alabama,1/4/2014,355.0,NaN,60.0,NaN,10.0,NaN,20.0,NaN,NaN,12.0,87.0,18.0,NaN
1,Alabama,1/11/2014,872.0,23.0,163.0,23.0,35.0,32.0,61.0,14.0,22.0,25.0,199.0,40.0,NaN
2,Alabama,1/18/2014,1044.0,21.0,209.0,34.0,31.0,33.0,77.0,19.0,24.0,19.0,242.0,60.0,NaN
3,Alabama,1/25/2014,1022.0,25.0,205.0,23.0,25.0,42.0,74.0,16.0,22.0,35.0,249.0,53.0,NaN
4,Alabama,2/1/2014,1040.0,18.0,200.0,26.0,38.0,26.0,68.0,15.0,18.0,24.0,269.0,50.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5339,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
5340,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
5341,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
5342,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
5343,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [3]:
# Jurisdictions with bad data that need to be isolated and dropped plus the dataframe containing aggregated data are extracted 

# Array of jurisdictions to drop
juri_interest = ["United States", "North Carolina", "District of Columbia", "Puerto Rico", "Connecticut"]

# Empty array to hold dataframes is defined
state_interest_df = []

# For loop adds dataframes of interest to an array where each entry is the dataframe to be examined
for state in juri_interest:
    state_interest_df.append(death_2014_2020_df.loc[death_2014_2020_df["jurisdiction"]==state])


state_interest_df[0]

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
13833,United States,1/4/2014,30889.0,494.0,6393.0,961.0,999.0,926.0,1975.0,424.0,542.0,363.0,7504.0,1563.0,NaN
13834,United States,1/11/2014,55715.0,896.0,11371.0,1722.0,1894.0,1886.0,3404.0,835.0,1085.0,646.0,13517.0,2703.0,NaN
13835,United States,1/18/2014,54681.0,919.0,11465.0,1659.0,1904.0,1916.0,3329.0,807.0,1050.0,597.0,12911.0,2707.0,NaN
13836,United States,1/25/2014,54175.0,845.0,11606.0,1599.0,1862.0,1760.0,3466.0,753.0,1028.0,624.0,12793.0,2720.0,NaN
13837,United States,2/1/2014,54049.0,890.0,11575.0,1584.0,1862.0,1639.0,3279.0,719.0,995.0,665.0,12902.0,2696.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5339,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
5340,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
5341,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
5342,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
5343,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [7]:
# Reset all indices for relevant dataframes
for df in state_interest_df:
    df.reset_index(inplace=True)
    df.drop("index", axis=1, inplace = True)

state_interest_df[0]

C:\Users\Jack Ruggles\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,United States,1/4/2014,30889.0,494.0,6393.0,961.0,999.0,926.0,1975.0,424.0,542.0,363.0,7504.0,1563.0,NaN
1,United States,1/11/2014,55715.0,896.0,11371.0,1722.0,1894.0,1886.0,3404.0,835.0,1085.0,646.0,13517.0,2703.0,NaN
2,United States,1/18/2014,54681.0,919.0,11465.0,1659.0,1904.0,1916.0,3329.0,807.0,1050.0,597.0,12911.0,2707.0,NaN
3,United States,1/25/2014,54175.0,845.0,11606.0,1599.0,1862.0,1760.0,3466.0,753.0,1028.0,624.0,12793.0,2720.0,NaN
4,United States,2/1/2014,54049.0,890.0,11575.0,1584.0,1862.0,1639.0,3279.0,719.0,995.0,665.0,12902.0,2696.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
356,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
357,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
358,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
359,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [42]:
# Dates to drop, being standardized, are formed into a list

# Dates before the date to drop are made into an initial list
drop = state_interest_df[0].loc[state_interest_df[0]["week_end_date"]=="10/11/2014"].index[0]-1
dates_to_drop_init = state_interest_df[0].loc[:drop]["week_end_date"]

# Dates following the desired end date are appended to the list
drop = state_interest_df[0].loc[state_interest_df[0]["week_end_date"]=="10/3/2020"].index[0]
dates_to_drop = dates_to_drop_init.append(state_interest_df[0].loc[drop:]["week_end_date"])


dates_to_drop

0        1/4/2014
1       1/11/2014
2       1/18/2014
3       1/25/2014
4        2/1/2014
5        2/8/2014
6       2/15/2014
7       2/22/2014
8        3/1/2014
9        3/8/2014
10      3/15/2014
11      3/22/2014
12      3/29/2014
13       4/5/2014
14      4/12/2014
15      4/19/2014
16      4/26/2014
17       5/3/2014
18      5/10/2014
19      5/17/2014
20      5/24/2014
21      5/31/2014
22       6/7/2014
23      6/14/2014
24      6/21/2014
25      6/28/2014
26       7/5/2014
27      7/12/2014
28      7/19/2014
29      7/26/2014
30       8/2/2014
31       8/9/2014
32      8/16/2014
33      8/23/2014
34      8/30/2014
35       9/6/2014
36      9/13/2014
37      9/20/2014
38      9/27/2014
39      10/4/2014
352     10/3/2020
353    10/10/2020
354    10/17/2020
355    10/24/2020
356    10/31/2020
357     11/7/2020
358    11/14/2020
359    11/21/2020
Name: week_end_date, dtype: object

In [43]:
for df in state_interest_df:
    df