In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Grab relevant dataframes and append them
death_2014_2018_df = pd.read_csv("data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2014-2018_studydata.csv")
death_2019_2020_df = pd.read_csv("data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2019-2020_studydata.csv")
death_2014_2020_df = death_2014_2018_df.append(death_2019_2020_df)


death_2014_2020_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,Alabama,1/4/2014,355.0,NaN,60.0,NaN,10.0,NaN,20.0,NaN,NaN,12.0,87.0,18.0,NaN
1,Alabama,1/11/2014,872.0,23.0,163.0,23.0,35.0,32.0,61.0,14.0,22.0,25.0,199.0,40.0,NaN
2,Alabama,1/18/2014,1044.0,21.0,209.0,34.0,31.0,33.0,77.0,19.0,24.0,19.0,242.0,60.0,NaN
3,Alabama,1/25/2014,1022.0,25.0,205.0,23.0,25.0,42.0,74.0,16.0,22.0,35.0,249.0,53.0,NaN
4,Alabama,2/1/2014,1040.0,18.0,200.0,26.0,38.0,26.0,68.0,15.0,18.0,24.0,269.0,50.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5339,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
5340,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
5341,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
5342,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
5343,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [3]:
# Jurisdictions with bad data that need to be isolated and dropped plus the dataframe containing aggregated data are extracted 

# Array of jurisdictions to drop
juri_interest = ["United States", "North Carolina", "District of Columbia", "Puerto Rico", "Connecticut"]

# Empty array to hold dataframes is defined
state_interest_df = []

# For loop adds dataframes of interest to an array where each entry is the dataframe to be examined
for state in juri_interest:
    state_interest_df.append(death_2014_2020_df.loc[death_2014_2020_df["jurisdiction"]==state])


state_interest_df[0]

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
13833,United States,1/4/2014,30889.0,494.0,6393.0,961.0,999.0,926.0,1975.0,424.0,542.0,363.0,7504.0,1563.0,NaN
13834,United States,1/11/2014,55715.0,896.0,11371.0,1722.0,1894.0,1886.0,3404.0,835.0,1085.0,646.0,13517.0,2703.0,NaN
13835,United States,1/18/2014,54681.0,919.0,11465.0,1659.0,1904.0,1916.0,3329.0,807.0,1050.0,597.0,12911.0,2707.0,NaN
13836,United States,1/25/2014,54175.0,845.0,11606.0,1599.0,1862.0,1760.0,3466.0,753.0,1028.0,624.0,12793.0,2720.0,NaN
13837,United States,2/1/2014,54049.0,890.0,11575.0,1584.0,1862.0,1639.0,3279.0,719.0,995.0,665.0,12902.0,2696.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5339,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
5340,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
5341,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
5342,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
5343,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [4]:
# Dates to drop, being standardized, are formed into a list

# Dates before the date to drop are made into an initial list
drop = state_interest_df[0].loc[state_interest_df[0]["week_end_date"]=="10/11/2014"].index[0]-1
dates_to_drop_init = state_interest_df[0].loc[:drop]["week_end_date"]

# Dates following the desired end date are appended to the list
drop = state_interest_df[0].loc[state_interest_df[0]["week_end_date"]=="10/3/2020"].index[0]
dates_to_drop = dates_to_drop_init.append(state_interest_df[0].loc[drop:]["week_end_date"])


dates_to_drop

13833      1/4/2014
13834     1/11/2014
13835     1/18/2014
13836     1/25/2014
13837      2/1/2014
13838      2/8/2014
13839     2/15/2014
13840     2/22/2014
13841      3/1/2014
13842      3/8/2014
13843     3/15/2014
13844     3/22/2014
13845     3/29/2014
13846      4/5/2014
13847     4/12/2014
13848     4/19/2014
13849     4/26/2014
13850      5/3/2014
13851     5/10/2014
13852     5/17/2014
13853     5/24/2014
13854     5/31/2014
13855      6/7/2014
13856     6/14/2014
13857     6/21/2014
13858     6/28/2014
13859      7/5/2014
13860     7/12/2014
13861     7/19/2014
13862     7/26/2014
13863      8/2/2014
13864      8/9/2014
13865     8/16/2014
13866     8/23/2014
13867     8/30/2014
13868      9/6/2014
13869     9/13/2014
13870     9/20/2014
13871     9/27/2014
13872     10/4/2014
5336      10/3/2020
5337     10/10/2020
5338     10/17/2020
5339     10/24/2020
5340     10/31/2020
5341      11/7/2020
5342     11/14/2020
5343     11/21/2020
Name: week_end_date, dtype: object

In [7]:
# Reset all indices and drop unwanted dates for relevant dataframes

# Empty array to hold cleaned dataframes is initialized
cleaned_df_array = []

# Find length of array holding dataframes
len_states = len(state_interest_df)

# Every dataframe in thearray of dataframes is cleaned identically
for i in range(len_states):
    
    # dataframe only containing wanted values is initialized, then the indices is reset with the result appended to the array
    #    of cleaned dataframes
    df = state_interest_df[i][state_interest_df[i]["week_end_date"].isin(dates_to_drop) == False]
    df.reset_index(inplace=True)
    df.drop("index", axis=1, inplace = True)
    cleaned_df_array.append(df)
    

cleaned_df_array[0]

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,United States,10/11/2014,49460.0,709.0,11524.0,1458.0,1837.0,841.0,2536.0,646.0,898.0,643.0,11395.0,2471.0,NaN
1,United States,10/18/2014,49322.0,727.0,11415.0,1395.0,1880.0,874.0,2542.0,672.0,853.0,612.0,11615.0,2584.0,NaN
2,United States,10/25/2014,49137.0,698.0,11457.0,1400.0,1923.0,844.0,2571.0,664.0,868.0,622.0,11372.0,2643.0,NaN
3,United States,11/1/2014,49037.0,728.0,11417.0,1367.0,1929.0,881.0,2612.0,637.0,886.0,574.0,11222.0,2603.0,NaN
4,United States,11/8/2014,51055.0,732.0,11514.0,1463.0,2050.0,830.0,2760.0,689.0,853.0,696.0,11897.0,2712.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,United States,8/29/2020,60296.0,722.0,11484.0,1840.0,2399.0,671.0,2520.0,731.0,972.0,1508.0,12158.0,2947.0,5051.0
308,United States,9/5/2020,58814.0,686.0,11187.0,1770.0,2458.0,723.0,2486.0,775.0,905.0,1589.0,12042.0,2800.0,4271.0
309,United States,9/12/2020,57540.0,670.0,11116.0,1795.0,2266.0,668.0,2468.0,718.0,901.0,1776.0,11702.0,2950.0,3884.0
310,United States,9/19/2020,57199.0,717.0,11213.0,1742.0,2297.0,677.0,2407.0,762.0,879.0,1809.0,11966.0,2835.0,3527.0
311,United States,9/26/2020,58026.0,718.0,11460.0,1724.0,2404.0,687.0,2526.0,756.0,886.0,1997.0,11969.0,2939.0,3543.0