In [5]:
# Import dependencies
import pandas as pd

In [14]:
# Grab relevant death data dataframes and append them, fill all missing values with 0, then reset index
death_2014_2019_df = pd.read_csv("../Data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2014-2019_2021-01-21.csv")
death_2020_2021_df = pd.read_csv("../Data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2020-2021_2021-01-21.csv")
death_2014_2021_data = death_2014_2019_df.append(death_2020_2021_df)
death_2014_2021_data.fillna(0, inplace = True)
death_2014_2021_df = death_2014_2021_data.reset_index().drop("index", axis=1)

# Normalization dataframe is imported
norm_df = pd.read_csv("../Data/normalization_year.csv")
norm_year = norm_df.columns

death_2014_2021_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,United States,1/4/2014,54065.0,882.0,11244.0,1654.0,1780.0,1639.0,3331.0,756.0,965.0,679.0,13166.0,2669.0,0.0
1,United States,1/11/2014,56353.0,905.0,11504.0,1735.0,1917.0,1910.0,3444.0,845.0,1098.0,665.0,13663.0,2738.0,0.0
2,United States,1/18/2014,54769.0,919.0,11496.0,1660.0,1914.0,1920.0,3333.0,812.0,1056.0,598.0,12928.0,2714.0,0.0
3,United States,1/25/2014,54223.0,845.0,11629.0,1602.0,1862.0,1765.0,3467.0,753.0,1029.0,622.0,12813.0,2720.0,0.0
4,United States,2/1/2014,54074.0,890.0,11584.0,1586.0,1867.0,1642.0,3283.0,720.0,998.0,664.0,12896.0,2699.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19811,Puerto Rico,12/12/2020,119.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0
19812,Puerto Rico,12/19/2020,128.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0
19813,Puerto Rico,12/26/2020,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0
19814,Puerto Rico,1/2/2021,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
19815,Puerto Rico,1/9/2021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
# Jurisdictions with bad data that need to be isolated and dropped plus the dataframe containing aggregated data are extracted 

# Array of jurisdictions to drop
juri_to_drop = ["North Carolina", "District of Columbia", "Puerto Rico", "Connecticut"]


# For loop adds dataframes of interest to an array where each entry is the dataframe to be examined
state_drop_df = death_2014_2021_df.loc[death_2014_2021_df["jurisdiction"].isin(juri_to_drop) == True]
united_df = death_2014_2021_df.loc[death_2014_2021_df["jurisdiction"]=="United States"]


united_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,United States,1/4/2014,54065.0,882.0,11244.0,1654.0,1780.0,1639.0,3331.0,756.0,965.0,679.0,13166.0,2669.0,0.0
1,United States,1/11/2014,56353.0,905.0,11504.0,1735.0,1917.0,1910.0,3444.0,845.0,1098.0,665.0,13663.0,2738.0,0.0
2,United States,1/18/2014,54769.0,919.0,11496.0,1660.0,1914.0,1920.0,3333.0,812.0,1056.0,598.0,12928.0,2714.0,0.0
3,United States,1/25/2014,54223.0,845.0,11629.0,1602.0,1862.0,1765.0,3467.0,753.0,1029.0,622.0,12813.0,2720.0,0.0
4,United States,2/1/2014,54074.0,890.0,11584.0,1586.0,1867.0,1642.0,3283.0,720.0,998.0,664.0,12896.0,2699.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16951,United States,12/12/2020,72174.0,719.0,10849.0,1953.0,2737.0,857.0,2714.0,881.0,989.0,3167.0,12582.0,3160.0,15881.0
16952,United States,12/19/2020,66267.0,669.0,10201.0,1789.0,2703.0,797.0,2441.0,762.0,849.0,3203.0,11915.0,2929.0,14071.0
16953,United States,12/26/2020,53334.0,592.0,8642.0,1470.0,2303.0,682.0,2125.0,672.0,814.0,3161.0,10353.0,2477.0,8461.0
16954,United States,1/2/2021,44827.0,498.0,7451.0,1292.0,2098.0,642.0,1940.0,584.0,681.0,2978.0,9172.0,2163.0,5555.0
16955,United States,1/9/2021,36487.0,418.0,6070.0,1063.0,1728.0,536.0,1548.0,496.0,583.0,2398.0,7356.0,1752.0,4633.0

In [16]:
# Dates to drop, being standardized, are formed into a list

# Dates before the date to drop are made into an initial list
drop = united_df.loc[united_df["week_end_date"]=="10/11/2014"].index[0]-1
dates_to_drop_init = united_df.loc[:drop]["week_end_date"]

# Dates following the desired end date are appended to the list
drop = united_df.loc[united_df["week_end_date"]=="10/3/2020"].index[0]
dates_to_drop = dates_to_drop_init.append(united_df.loc[drop:]["week_end_date"])


dates_to_drop

0          1/4/2014
1         1/11/2014
2         1/18/2014
3         1/25/2014
4          2/1/2014
5          2/8/2014
6         2/15/2014
7         2/22/2014
8          3/1/2014
9          3/8/2014
10        3/15/2014
11        3/22/2014
12        3/29/2014
13         4/5/2014
14        4/12/2014
15        4/19/2014
16        4/26/2014
17         5/3/2014
18        5/10/2014
19        5/17/2014
20        5/24/2014
21        5/31/2014
22         6/7/2014
23        6/14/2014
24        6/21/2014
25        6/28/2014
26         7/5/2014
27        7/12/2014
28        7/19/2014
29        7/26/2014
30         8/2/2014
31         8/9/2014
32        8/16/2014
33        8/23/2014
34        8/30/2014
35         9/6/2014
36        9/13/2014
37        9/20/2014
38        9/27/2014
39        10/4/2014
16941     10/3/2020
16942    10/10/2020
16943    10/17/2020
16944    10/24/2020
16945    10/31/2020
16946     11/7/2020
16947    11/14/2020
16948    11/21/2020
16949    11/28/2020
16950     12/5/2020
16951    12/12/2020
16952    12/19/2020
16953    12/26/2020
16954      1/2/2021
16955      1/9/2021
Name: week_end_date, dtype: object

In [17]:
# Reset all indices and drop unwanted dates for relevant dataframes



# Both dataframes are trimmed of unwanted dates.  United also has index reset.
cleaned_united_df = united_df[united_df["week_end_date"].isin(dates_to_drop) == False].reset_index().drop("index", axis=1)
cleaned_state_drop_df = state_drop_df[state_drop_df["week_end_date"].isin(dates_to_drop) == False]

cleaned_united_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,United States,10/11/2014,49499.0,712.0,11540.0,1457.0,1840.0,842.0,2541.0,649.0,902.0,652.0,11397.0,2467.0,0.0
1,United States,10/18/2014,49427.0,726.0,11454.0,1398.0,1890.0,882.0,2550.0,672.0,854.0,626.0,11633.0,2591.0,0.0
2,United States,10/25/2014,49252.0,698.0,11479.0,1409.0,1933.0,851.0,2586.0,667.0,871.0,629.0,11401.0,2649.0,0.0
3,United States,11/1/2014,49193.0,731.0,11467.0,1371.0,1937.0,881.0,2620.0,634.0,887.0,593.0,11261.0,2605.0,0.0
4,United States,11/8/2014,51214.0,736.0,11554.0,1468.0,2056.0,831.0,2771.0,692.0,856.0,728.0,11923.0,2718.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,United States,8/29/2020,60779.0,728.0,11544.0,1867.0,2419.0,676.0,2545.0,743.0,978.0,1069.0,12361.0,2969.0,5091.0
308,United States,9/5/2020,59756.0,704.0,11317.0,1806.0,2492.0,731.0,2531.0,795.0,920.0,1105.0,12329.0,2846.0,4363.0
309,United States,9/12/2020,59050.0,693.0,11378.0,1865.0,2315.0,680.0,2546.0,744.0,920.0,1201.0,12159.0,3024.0,3986.0
310,United States,9/19/2020,58921.0,744.0,11526.0,1824.0,2346.0,701.0,2496.0,777.0,916.0,1208.0,12475.0,2912.0,3644.0
311,United States,9/26/2020,59489.0,744.0,11691.0,1796.0,2455.0,720.0,2624.0,780.0,911.0,1243.0,12406.0,3018.0,3648.0

In [18]:
# Dataframes of values to be subtracted from United States values is crafted. Note that the indexing changes.
bad_values = cleaned_state_drop_df.groupby("week_end_date").sum().reset_index()
bad_values

,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,1/10/2015,3523.0,66.0,664.0,142.0,179.0,154.0,210.0,45.0,71.0,27.0,758.0,179.0,0.0
1,1/11/2020,3334.0,61.0,656.0,128.0,169.0,91.0,179.0,39.0,53.0,37.0,640.0,176.0,0.0
2,1/12/2019,3321.0,47.0,605.0,144.0,151.0,65.0,197.0,44.0,66.0,20.0,743.0,155.0,0.0
3,1/13/2018,3804.0,84.0,677.0,155.0,198.0,147.0,221.0,54.0,68.0,26.0,816.0,172.0,0.0
4,1/14/2017,3382.0,68.0,636.0,146.0,151.0,91.0,190.0,41.0,81.0,13.0,688.0,156.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,9/5/2015,2769.0,60.0,637.0,111.0,134.0,36.0,117.0,16.0,34.0,16.0,552.0,130.0,0.0
308,9/5/2020,3249.0,48.0,596.0,145.0,160.0,50.0,123.0,34.0,55.0,98.0,601.0,172.0,189.0
309,9/7/2019,2952.0,44.0,591.0,120.0,133.0,55.0,132.0,27.0,52.0,36.0,618.0,128.0,0.0
310,9/8/2018,2895.0,53.0,627.0,126.0,123.0,31.0,142.0,27.0,61.0,22.0,580.0,133.0,0.0
311,9/9/2017,2890.0,57.0,660.0,98.0,127.0,50.0,136.0,49.0,63.0,45.0,550.0,139.0,0.0

In [19]:
# Bad Values are subtracted from united states values to give Values without the excluded states
# Note that as the indexing differs, and the indexing must be preserved for the united states dataframes, a for loop going
#     through the rows will be used and a dataframe will be constructed from that.

# Empty dataframe holding final data is initialized. This is done as there is no empty value for jurisdiction.
final_df = cleaned_united_df.loc[cleaned_united_df["jurisdiction"] == ""]

# Count variable for the week in the flu season and the flu season itself are initialized
week = 1
season = 0

# For loop that goes through each row
for index, row in cleaned_united_df.iterrows():

    # Grabs the datum point from the bad_value_df corresponding to the correct date
    bad_datum = bad_values.loc[bad_values["week_end_date"] == row[1]]
    
    # Temporary dataframe holding only the one datum point for that date.
    # Relevant data has bad data subtracted from wanted, then multiplied by the normalization factor
    # Columns for season and week are added for ease later
    temp_df = pd.DataFrame([[row[0],
                             row[1],
                             week,
                             season,
                             float(row[2] - bad_datum["all_cause"]) * float(norm_df[norm_year[season]]),
                             float(row[3] - bad_datum["septicemia"]) * float(norm_df[norm_year[season]]),
                             float(row[4] - bad_datum["cancer"]) * float(norm_df[norm_year[season]]),
                             float(row[5] - bad_datum["diabetes"]) * float(norm_df[norm_year[season]]),
                             float(row[6] - bad_datum["Alzheimers"]) * float(norm_df[norm_year[season]]),
                             float(row[7] - bad_datum["influenza_pneumonia"]) * float(norm_df[norm_year[season]]),
                             float(row[8] - bad_datum["chronic_LRD"]) * float(norm_df[norm_year[season]]),
                             float(row[9] - bad_datum["other_respiratory"]) * float(norm_df[norm_year[season]]),
                             float(row[10] - bad_datum["kidney"]) * float(norm_df[norm_year[season]]),
                             float(row[11] - bad_datum["NEC"]) * float(norm_df[norm_year[season]]),
                             float(row[12] - bad_datum["heart_disease"]) * float(norm_df[norm_year[season]]),
                             float(row[13] - bad_datum["CBVD"]) * float(norm_df[norm_year[season]]),
                             float(row[14] - bad_datum["COVID19_UCOD"]) * float(norm_df[norm_year[season]])
                            ]],
                           columns=["jurisdiction", "week_end_date", "season_week", "season", "all_cause", "septicemia",\
                                    "cancer", "diabetes", "Alzheimers", "influenza_pneumonia", "chronic_LRD",\
                                    "other_respiratory", "kidney", "NEC", "heart_disease", "CBVD", "COVID19_UCOD"
                 ])
    
    # Row for specific data is appended to dataframe
    final_df = final_df.append(temp_df, ignore_index = True)
    
    # Checks are made for week in flu season.  If flu season over, start next one, otherwise add 1 week.
    if week == 52:
        week = 1
        season+=1
    else:
        week+=1

final_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD,season_week,season
0,United States,10/11/2014,47936.706552,672.086975,11269.826525,1341.081525,1750.312397,799.907197,2467.754935,627.762220,863.817308,643.224344,11135.821454,2394.567549,0.0,1.0,0.0
1,United States,10/18/2014,47948.045442,712.288496,11135.821454,1298.818387,1820.407358,855.570842,2490.432716,644.255152,801.968813,629.823837,11375.999774,2527.541813,0.0,2.0,0.0
2,United States,10/25/2014,47709.928738,648.378385,11158.499235,1312.218894,1862.670496,835.985485,2531.665046,661.778892,821.554170,619.515754,11130.667412,2550.219594,0.0,3.0,0.0
3,United States,11/1/2014,47638.802969,709.196071,11166.745701,1266.863331,1879.163428,855.570842,2537.849895,617.454138,837.016294,596.837973,10964.707285,2510.018073,0.0,4.0,0.0
4,United States,11/8/2014,49680.834100,697.857181,11222.409346,1376.129005,1979.151827,815.369321,2709.994872,676.210208,823.615786,718.473346,11670.810932,2660.516076,0.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,United States,8/29/2020,57553.000000,699.000000,10957.000000,1727.000000,2271.000000,629.000000,2428.000000,712.000000,925.000000,976.000000,11755.000000,2807.000000,4913.0,48.0,5.0
308,United States,9/5/2020,56507.000000,656.000000,10721.000000,1661.000000,2332.000000,681.000000,2408.000000,761.000000,865.000000,1007.000000,11728.000000,2674.000000,4174.0,49.0,5.0
309,United States,9/12/2020,56005.000000,640.000000,10783.000000,1741.000000,2186.000000,654.000000,2412.000000,707.000000,873.000000,1113.000000,11584.000000,2882.000000,3804.0,50.0,5.0
310,United States,9/19/2020,55923.000000,705.000000,10944.000000,1691.000000,2225.000000,665.000000,2369.000000,756.000000,851.000000,1111.000000,11893.000000,2777.000000,3461.0,51.0,5.0
311,United States,9/26/2020,56905.000000,705.000000,11219.000000,1686.000000,2332.000000,702.000000,2505.000000,742.000000,867.000000,1171.000000,11887.000000,2893.000000,3514.0,52.0,5.0

In [20]:
# Export final dataframe to csv
final_df.to_csv("../Data/final_death_data.csv", index=False)