In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Grab relevant death data dataframes and append them, then fill all missing values with 0
death_2014_2018_df = pd.read_csv("../Data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2014-2018_studydata.csv")
death_2019_2020_df = pd.read_csv("../Data/Weekly_Counts_of_Deaths_by_State_and_Select_Causes__2019-2020_studydata.csv")
death_2014_2020_df = death_2014_2018_df.append(death_2019_2020_df)
death_2014_2020_df.fillna(0, inplace = True)

# Normalization dataframe is imported
norm_df = pd.read_csv("../Data/normalization_year.csv")
norm_year = norm_df.columns

death_2014_2020_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,Alabama,1/4/2014,355.0,0.0,60.0,0.0,10.0,0.0,20.0,0.0,0.0,12.0,87.0,18.0,0.0
1,Alabama,1/11/2014,872.0,23.0,163.0,23.0,35.0,32.0,61.0,14.0,22.0,25.0,199.0,40.0,0.0
2,Alabama,1/18/2014,1044.0,21.0,209.0,34.0,31.0,33.0,77.0,19.0,24.0,19.0,242.0,60.0,0.0
3,Alabama,1/25/2014,1022.0,25.0,205.0,23.0,25.0,42.0,74.0,16.0,22.0,35.0,249.0,53.0,0.0
4,Alabama,2/1/2014,1040.0,18.0,200.0,26.0,38.0,26.0,68.0,15.0,18.0,24.0,269.0,50.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5339,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
5340,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
5341,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
5342,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
5343,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [3]:
# Jurisdictions with bad data that need to be isolated and dropped plus the dataframe containing aggregated data are extracted 

# Array of jurisdictions to drop
juri_to_drop = ["North Carolina", "District of Columbia", "Puerto Rico", "Connecticut"]


# For loop adds dataframes of interest to an array where each entry is the dataframe to be examined
state_drop_df = death_2014_2020_df.loc[death_2014_2020_df["jurisdiction"].isin(juri_to_drop) == True]
united_df = death_2014_2020_df.loc[death_2014_2020_df["jurisdiction"]=="United States"]


united_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
13833,United States,1/4/2014,30889.0,494.0,6393.0,961.0,999.0,926.0,1975.0,424.0,542.0,363.0,7504.0,1563.0,0.0
13834,United States,1/11/2014,55715.0,896.0,11371.0,1722.0,1894.0,1886.0,3404.0,835.0,1085.0,646.0,13517.0,2703.0,0.0
13835,United States,1/18/2014,54681.0,919.0,11465.0,1659.0,1904.0,1916.0,3329.0,807.0,1050.0,597.0,12911.0,2707.0,0.0
13836,United States,1/25/2014,54175.0,845.0,11606.0,1599.0,1862.0,1760.0,3466.0,753.0,1028.0,624.0,12793.0,2720.0,0.0
13837,United States,2/1/2014,54049.0,890.0,11575.0,1584.0,1862.0,1639.0,3279.0,719.0,995.0,665.0,12902.0,2696.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5339,United States,10/24/2020,57578.0,673.0,10956.0,1620.0,2443.0,715.0,2481.0,741.0,865.0,2595.0,11520.0,2846.0,4822.0
5340,United States,10/31/2020,57367.0,638.0,10651.0,1704.0,2304.0,711.0,2344.0,748.0,841.0,2727.0,11485.0,2872.0,5453.0
5341,United States,11/7/2020,58120.0,661.0,10594.0,1627.0,2408.0,682.0,2503.0,718.0,871.0,3131.0,11288.0,2754.0,6431.0
5342,United States,11/14/2020,54002.0,606.0,9825.0,1461.0,2307.0,676.0,2222.0,698.0,808.0,2848.0,10270.0,2587.0,6706.0
5343,United States,11/21/2020,39427.0,436.0,7420.0,1103.0,1748.0,503.0,1677.0,552.0,606.0,2192.0,7589.0,1930.0,4647.0

In [4]:
# Dates to drop, being standardized, are formed into a list

# Dates before the date to drop are made into an initial list
drop = united_df.loc[united_df["week_end_date"]=="10/11/2014"].index[0]-1
dates_to_drop_init = united_df.loc[:drop]["week_end_date"]

# Dates following the desired end date are appended to the list
drop = united_df.loc[united_df["week_end_date"]=="10/3/2020"].index[0]
dates_to_drop = dates_to_drop_init.append(united_df.loc[drop:]["week_end_date"])


dates_to_drop

13833      1/4/2014
13834     1/11/2014
13835     1/18/2014
13836     1/25/2014
13837      2/1/2014
13838      2/8/2014
13839     2/15/2014
13840     2/22/2014
13841      3/1/2014
13842      3/8/2014
13843     3/15/2014
13844     3/22/2014
13845     3/29/2014
13846      4/5/2014
13847     4/12/2014
13848     4/19/2014
13849     4/26/2014
13850      5/3/2014
13851     5/10/2014
13852     5/17/2014
13853     5/24/2014
13854     5/31/2014
13855      6/7/2014
13856     6/14/2014
13857     6/21/2014
13858     6/28/2014
13859      7/5/2014
13860     7/12/2014
13861     7/19/2014
13862     7/26/2014
13863      8/2/2014
13864      8/9/2014
13865     8/16/2014
13866     8/23/2014
13867     8/30/2014
13868      9/6/2014
13869     9/13/2014
13870     9/20/2014
13871     9/27/2014
13872     10/4/2014
5336      10/3/2020
5337     10/10/2020
5338     10/17/2020
5339     10/24/2020
5340     10/31/2020
5341      11/7/2020
5342     11/14/2020
5343     11/21/2020
Name: week_end_date, dtype: object

In [5]:
# Reset all indices and drop unwanted dates for relevant dataframes



# Both dataframes are trimmed of unwanted dates.  United also has index reset.
cleaned_united_df = united_df[united_df["week_end_date"].isin(dates_to_drop) == False].reset_index().drop("index", axis=1)
cleaned_state_drop_df = state_drop_df[state_drop_df["week_end_date"].isin(dates_to_drop) == False]

cleaned_united_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,United States,10/11/2014,49460.0,709.0,11524.0,1458.0,1837.0,841.0,2536.0,646.0,898.0,643.0,11395.0,2471.0,0.0
1,United States,10/18/2014,49322.0,727.0,11415.0,1395.0,1880.0,874.0,2542.0,672.0,853.0,612.0,11615.0,2584.0,0.0
2,United States,10/25/2014,49137.0,698.0,11457.0,1400.0,1923.0,844.0,2571.0,664.0,868.0,622.0,11372.0,2643.0,0.0
3,United States,11/1/2014,49037.0,728.0,11417.0,1367.0,1929.0,881.0,2612.0,637.0,886.0,574.0,11222.0,2603.0,0.0
4,United States,11/8/2014,51055.0,732.0,11514.0,1463.0,2050.0,830.0,2760.0,689.0,853.0,696.0,11897.0,2712.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,United States,8/29/2020,60296.0,722.0,11484.0,1840.0,2399.0,671.0,2520.0,731.0,972.0,1508.0,12158.0,2947.0,5051.0
308,United States,9/5/2020,58814.0,686.0,11187.0,1770.0,2458.0,723.0,2486.0,775.0,905.0,1589.0,12042.0,2800.0,4271.0
309,United States,9/12/2020,57540.0,670.0,11116.0,1795.0,2266.0,668.0,2468.0,718.0,901.0,1776.0,11702.0,2950.0,3884.0
310,United States,9/19/2020,57199.0,717.0,11213.0,1742.0,2297.0,677.0,2407.0,762.0,879.0,1809.0,11966.0,2835.0,3527.0
311,United States,9/26/2020,58026.0,718.0,11460.0,1724.0,2404.0,687.0,2526.0,756.0,886.0,1997.0,11969.0,2939.0,3543.0

In [6]:
# Dataframes of values to be subtracted from United States values is crafted. Note that the indexing changes.
bad_values = cleaned_state_drop_df.groupby("week_end_date").sum().reset_index()
bad_values

,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD
0,1/10/2015,3531.0,67.0,665.0,142.0,179.0,154.0,210.0,45.0,71.0,10.0,762.0,179.0,0.0
1,1/11/2020,3335.0,61.0,657.0,128.0,169.0,91.0,179.0,39.0,53.0,54.0,639.0,176.0,0.0
2,1/12/2019,3330.0,47.0,606.0,144.0,151.0,66.0,197.0,54.0,66.0,20.0,746.0,155.0,0.0
3,1/13/2018,3814.0,85.0,678.0,157.0,198.0,147.0,221.0,54.0,69.0,16.0,817.0,172.0,0.0
4,1/14/2017,3390.0,68.0,638.0,146.0,151.0,91.0,190.0,41.0,81.0,14.0,692.0,156.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,9/5/2015,2774.0,60.0,639.0,111.0,134.0,36.0,127.0,16.0,34.0,13.0,555.0,131.0,0.0
308,9/5/2020,2522.0,33.0,478.0,122.0,127.0,44.0,92.0,19.0,42.0,91.0,469.0,137.0,119.0
309,9/7/2019,2957.0,44.0,591.0,121.0,133.0,55.0,132.0,27.0,52.0,32.0,619.0,128.0,0.0
310,9/8/2018,2901.0,53.0,627.0,126.0,123.0,31.0,142.0,27.0,61.0,11.0,584.0,133.0,0.0
311,9/9/2017,2899.0,57.0,660.0,98.0,127.0,51.0,136.0,49.0,63.0,41.0,555.0,139.0,0.0

In [7]:
# Bad Values are subtracted from united states values to give Values without the excluded states
# Note that as the indexing differs, and the indexing must be preserved for the united states dataframes, a for loop going
#     through the rows will be used and a dataframe will be constructed from that.

# Empty dataframe holding final data is initialized. This is done as there is no empty value for jurisdiction.
final_df = cleaned_united_df.loc[cleaned_united_df["jurisdiction"] == ""]

# Count variable for the week in the flu season and the flu season itself are initialized
week = 1
season = 0

# For loop that goes through each row
for index, row in cleaned_united_df.iterrows():

    # Grabs the datum point from the bad_value_df corresponding to the correct date
    bad_datum = bad_values.loc[bad_values["week_end_date"] == row[1]]
    
    # Temporary dataframe holding only the one datum point for that date.
    # Relevant data has bad data subtracted from wanted, then multiplied by the normalization factor
    # Columns for season and week are added for ease later
    temp_df = pd.DataFrame([[row[0],
                             row[1],
                             week,
                             season,
                             float(row[2] - bad_datum["all_cause"]) * float(norm_df[norm_year[season]]),
                             float(row[3] - bad_datum["septicemia"]) * float(norm_df[norm_year[season]]),
                             float(row[4] - bad_datum["cancer"]) * float(norm_df[norm_year[season]]),
                             float(row[5] - bad_datum["diabetes"]) * float(norm_df[norm_year[season]]),
                             float(row[6] - bad_datum["Alzheimers"]) * float(norm_df[norm_year[season]]),
                             float(row[7] - bad_datum["influenza_pneumonia"]) * float(norm_df[norm_year[season]]),
                             float(row[8] - bad_datum["chronic_LRD"]) * float(norm_df[norm_year[season]]),
                             float(row[9] - bad_datum["other_respiratory"]) * float(norm_df[norm_year[season]]),
                             float(row[10] - bad_datum["kidney"]) * float(norm_df[norm_year[season]]),
                             float(row[11] - bad_datum["NEC"]) * float(norm_df[norm_year[season]]),
                             float(row[12] - bad_datum["heart_disease"]) * float(norm_df[norm_year[season]]),
                             float(row[13] - bad_datum["CBVD"]) * float(norm_df[norm_year[season]]),
                             float(row[14] - bad_datum["COVID19_UCOD"]) * float(norm_df[norm_year[season]])
                            ]],
                           columns=["jurisdiction", "week_end_date", "season_week", "season", "all_cause", "septicemia",\
                                    "cancer", "diabetes", "Alzheimers", "influenza_pneumonia", "chronic_LRD",\
                                    "other_respiratory", "kidney", "NEC", "heart_disease", "CBVD", "COVID19_UCOD"
                 ])
    
    # Row for specific data is appended to dataframe
    final_df = final_df.append(temp_df, ignore_index = True)
    
    # Checks are made for week in flu season.  If flu season over, start next one, otherwise add 1 week.
    if week == 52:
        week = 1
        season+=1
    else:
        week+=1

final_df

,jurisdiction,week_end_date,all_cause,septicemia,cancer,diabetes,Alzheimers,influenza_pneumonia,chronic_LRD,other_respiratory,kidney,NEC,heart_disease,CBVD,COVID19_UCOD,season_week,season
0,United States,10/11/2014,47893.412605,668.994550,11253.333593,1342.112333,1747.219973,797.845580,2462.600894,624.669796,859.694075,633.947070,11132.729029,2398.690782,0.0,1.0,0.0
1,United States,10/18/2014,47834.656536,713.319304,11094.589124,1294.695154,1810.099275,847.324376,2481.155442,644.255152,800.938005,615.392521,11358.476034,2520.326155,0.0,2.0,0.0
2,United States,10/25/2014,47588.293365,648.378385,11136.852262,1301.910811,1852.362413,828.769828,2515.172114,658.686468,818.461745,612.300097,11098.712357,2544.034745,0.0,3.0,0.0
3,United States,11/1/2014,47476.966075,706.103647,11115.205289,1262.740098,1870.916962,855.570842,2529.603429,620.546563,835.985485,566.944534,10925.536572,2506.925648,0.0,4.0,0.0
4,United States,11/8/2014,49511.781548,693.733948,11181.177016,1369.944155,1972.966978,814.338512,2698.655981,673.117783,820.523362,684.456674,11642.979109,2654.331227,0.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,United States,8/29/2020,57355.000000,697.000000,10936.000000,1709.000000,2268.000000,627.000000,2417.000000,703.000000,923.000000,1408.000000,11613.000000,2799.000000,4892.0,48.0,5.0
308,United States,9/5/2020,56292.000000,653.000000,10709.000000,1648.000000,2331.000000,679.000000,2394.000000,756.000000,863.000000,1498.000000,11573.000000,2663.000000,4152.0,49.0,5.0
309,United States,9/12/2020,55724.000000,641.000000,10764.000000,1713.000000,2188.000000,655.000000,2399.000000,708.000000,880.000000,1715.000000,11369.000000,2872.000000,3784.0,50.0,5.0
310,United States,9/19/2020,55627.000000,706.000000,10918.000000,1660.000000,2222.000000,659.000000,2358.000000,762.000000,849.000000,1757.000000,11674.000000,2770.000000,3450.0,51.0,5.0
311,United States,9/26/2020,56515.000000,696.000000,11185.000000,1661.000000,2337.000000,687.000000,2480.000000,742.000000,866.000000,1942.000000,11650.000000,2872.000000,3486.0,52.0,5.0

In [8]:
# Export final dataframe to csv
final_df.to_csv("../Data/final_death_data.csv", index=False)